apiVersion: apps/v1
kind: Deployment
metadata:
  name: myecr1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: myecr
        image: public.ecr.aws/x1s1l1x2/myecr:latest
        ports:
        - containerPort: 8080
